Updated to work with multiple `scheduled` tags prefixed with the environment
yusinto/ld-scheduler pull request #2
Opened 2017-03-10 01:11 UTC by willmcpo

Made changes to make it work with multiple environments.

2017-03-10 03:30 UTC, yusinto commented on src/completeFlagDeployment.js
Nit: extraneous newline here

2017-03-10 03:47 UTC, yusinto requested changes
Thanks for the PR! I have a few comments which are minor, you could take a look that would be awesome. Thanks again!

2017-03-10 03:47 UTC, yusinto commented on src/completeFlagDeployment.js
Nit: Extraneous newline here

2017-03-10 03:47 UTC, yusinto commented on src/completeFlagDeployment.test.js
> +
Nit again: extraneous newline

2017-03-10 03:47 UTC, yusinto commented on src/scheduler.js
> +      log.info(`Found scheduled flag ${f.key} with targetDeploymentDateTime: ${targetDeploymentDateTime}. isScheduledTimePassed? ${isScheduledTimePassed}`);
This logging string will output ${targetDeploymentDateTime} in unix epoch elapsed format which is probably not what you want. Do you mean to format it in a more readable format?

2017-03-10 03:47 UTC, yusinto commented on README.md
> +3. Tag your feature flag. In launch darkly's dashboard, under the Settings tab of your feature flag, under Tags, add one or more "scheduled" tags, each prefixed with an environment name.
I have updated a new screenshot to reflect the tag changes. The new image link is [here](https://cloud.githubusercontent.com/assets/1593077/23781221/ddd4557e-059f-11e7-8e4f-601e6cf91f78.png)

2017-03-12 23:03 UTC, willmcpo commented
@yusinto ok changes made and prepublished. Can you review again? Thanks.

2017-03-12 23:30 UTC, yusinto approved these changes
Awesome stuff! Thanks @willmcpo !

2017-03-12 23:31 UTC, merged